<?php

declare(strict_types=1);

namespace App\Core;

/**
 * Application configuration loaded from the installer-generated /config.php.
 * Never contains user-editable business settings — those live in the `settings`
 * table and are read through SettingsService.
 */
final class Config
{
    private static array $items = [];
    private static bool $loaded = false;

    public static function load(): void
    {
        if (self::$loaded) {
            return;
        }
        self::$loaded = true;
        if (is_file(CONFIG_FILE)) {
            $data = require CONFIG_FILE;
            if (is_array($data)) {
                self::$items = $data;
            }
        }
        if (!isset(self::$items['app']['timezone'])) {
            self::$items['app']['timezone'] = 'Asia/Kolkata';
        }
    }

    public static function get(string $key, mixed $default = null): mixed
    {
        self::load();
        $value = self::$items;
        foreach (explode('.', $key) as $segment) {
            if (!is_array($value) || !array_key_exists($segment, $value)) {
                return $default;
            }
            $value = $value[$segment];
        }
        return $value;
    }

    public static function set(string $key, mixed $value): void
    {
        self::load();
        $segments = explode('.', $key);
        $ref = &self::$items;
        foreach ($segments as $segment) {
            if (!isset($ref[$segment]) || !is_array($ref[$segment])) {
                $ref[$segment] = [];
            }
            $ref = &$ref[$segment];
        }
        $ref = $value;
    }

    public static function all(): array
    {
        self::load();
        return self::$items;
    }

    /** Write the configuration file (installer + updater only). */
    public static function write(array $config): bool
    {
        $export = var_export($config, true);
        $contents = "<?php\n\n/**\n * ScrapX configuration — generated by the installer.\n"
            . " * This file is PROTECTED: the GitHub updater never overwrites it.\n */\n\n"
            . "return {$export};\n";
        $ok = file_put_contents(CONFIG_FILE, $contents, LOCK_EX) !== false;
        if ($ok) {
            @chmod(CONFIG_FILE, 0640);
            self::$items = $config;
            self::$loaded = true;
        }
        return $ok;
    }
}
